package model

type AutoGenerated struct {
	Users []GetUsers `json:"users"`
}

type GetUsers struct {
	ID        int    `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Age       int    `json:"age"`
}
